# Generated by Django 5.0 on 2023-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GlobalTalentConnect', '0002_usuario_email_usuario_pais_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
