# Generated by Django 5.0 on 2023-12-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GlobalTalentConnect', '0003_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(null=True),
        ),
    ]
