# Generated by Django 5.0 on 2023-12-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GlobalTalentConnect', '0004_alter_usuario_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais_trabalho',
            field=models.CharField(default='Brasil', max_length=255, null=True),
        ),
    ]
